import "./globals.css"
import type { Metadata } from "next"
import { Raleway } from "next/font/google"
import Providers from "./components/Providers"

const montserrat = Raleway({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<Providers>
				<body className={montserrat.className}>
					{children}
					<div id="modal_root"></div>
				</body>
			</Providers>
		</html>
	)
}
