import { SessionProvider } from "next-auth/react"
import "./globals.css"
import styles from "./page.module.css"
import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import Providers from "./components/Providers"

const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<Providers>
				<body className={`${montserrat.className} ${styles.body}`}>{children}</body>
			</Providers>
		</html>
	)
}
